name: Task1-EXTRA
env:
    DEPLOY_VER : ${{ github.sha }}
    YEAR       : "2022"


on: workflow_dispatch
        
 
  
 # push:  
 #   branches: [ main ]
 # pull_request:
 #   branches: [ main ]

 # Allows you to run this workflow manually from the Actions tab
 # workflow_dispatch: 

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  task1_extra_1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Print the list of files/directories in repository.
        run: ls -la

      # Runs a set of commands using the runners shell
      - name: Print content of log.txt file
        run: cat Task1/log.txt
        
      - name: Print “Hello from “DEPLOY_VER variable’s content” commit”
        run: echo “Hello from $DEPLOY_VER commit”
          
 
  task1_extra_2:
    
    runs-on: ubuntu-latest
    needs  : [task1_extra_1]
    env    : 
           MONTH : "August" 
            
    steps:
      - uses: actions/checkout@v2   
             
      - name: Print system date and time
        run: date
        
      - name: Print variable’s content  
        run: |
          echo Day - $DAY_OF_THE_MONTH;
          echo Month - $MONTH;
          echo Year - $YEAR.
        env : 
           DAY_OF_THE_MONTH : 17   
  
          
      - name: Print secret favorite day of week
        run: echo ${{ secrets.FAVORITE_DAY_OF_WEEK }}
        
