# This is a basic workflow to help you get started with Actions

name: Task1-EXTRA
env:
    DEPLOY_VER : ${{ github.sha }}
    YEAR       : "2022"

# Controls when the workflow will run
on: workflow_dispatch
        
  # Triggers the workflow on push or pull request events but only for the main branch
  
 #   [push, workflow_dispatch]
  
 #   branches: [ main, workflow_dispatch ]
 # pull_request:
 #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Print the list of files/directories in repository.
        run: ls -la

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cat Task1/log.txt
          echo “Hello from ${{ env.DEPLOY_VER }} commit”
